version: "3"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/

  rabbit:
    image: rabbitmq:3-management

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn moviemate.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/code/static
    depends_on:
      - db
      - rabbit

  celery:
    build:
      context: .
      dockerfile: Dockerfile.selenium.prod
    command: celery -A moviemate worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - rabbit

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A moviemate beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - rabbit

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/code/static
    ports:
      - "8082:80"
      - "8443:443"
    depends_on:
      - backend

volumes:
  pg_data:
  static_volume:
