version: "3"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/

  rabbit:
    image: rabbitmq:3-management

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn moviemate.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/code/static
    depends_on:
      - db
      - rabbit

  celery:
    build:
      context: .
      dockerfile: Dockerfile.selenium.prod
    command: celery -A moviemate worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - rabbit

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A moviemate beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - rabbit

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      - static_volume:/code/static
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend
      - certbot

  certbot:
    image: certbot/certbot:v2.6.0
    env_file:
      - .env
    command: certonly --webroot --webroot-path=/var/www/certbot/ -d ${CERTBOT_HOST} --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --keep
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  pg_data:
  static_volume:
