# Base image
FROM python:3.10-slim-buster

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set working directory
WORKDIR /code

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Expose the port
EXPOSE 8000

# Run Gunicorn
CMD ["gunicorn", "moviemate.wsgi:application", "--bind", "0.0.0.0:8000"]