# Generated by Django 4.2 on 2023-05-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaInCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema', to='scraper.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('cinema_in_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='scraper.cinemaincity')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='')),
                ('booking_link', models.URLField(default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='scraper.city')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='scraper.film')),
            ],
        ),
        migrations.AddField(
            model_name='cinemaincity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='scraper.city'),
        ),
        migrations.AddField(
            model_name='cinemaincity',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='scraper.scraperdata'),
        ),
    ]
