# Generated by Django 4.2 on 2023-05-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperall',
            name='booking_link',
            field=models.URLField(default='', unique=True),
        ),
    ]
