# Generated by Django 4.2 on 2023-05-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
