# Generated by Django 4.2 on 2023-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='date',
            new_name='show_info',
        ),
        migrations.AddField(
            model_name='showtime',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
