# Generated by Django 4.2 on 2023-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(null=True),
        ),
    ]
