# Generated by Django 4.2 on 2023-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_film_category_film_image_url_alter_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
