# Generated by Django 4.2 on 2023-05-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_date_showtime_show_info_showtime_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='release_date',
            new_name='show_info',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='show_info',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='filmtimes',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='description',
        ),
        migrations.AddField(
            model_name='filmtimes',
            name='film',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='filmtime', to='scraper.film'),
            preserve_default=False,
        ),
    ]
