# Generated by Django 4.2 on 2023-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_movie_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
