# Generated by Django 4.2 on 2023-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_film_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(),
        ),
    ]
