name: Quality Assurance

on:
  pull_request:
  workflow_call:
    inputs:
      SECRET_KEY:
        required: true
        type: string
      ALLOWED_HOSTS:
        required: true
        type: string
      CORS_ALLOWED_ORIGINS:
        required: true
        type: string
      DB_USER:
        required: true
        type: string
      DB_PASSWORD:
        required: true
        type: string
      DB_NAME:
        required: true
        type: string
      DB_HOST:
        required: true
        type: string
      DB_HOST_TEST:
        required: true
        type: string
      CELERY_BROKER_URL:
        required: true
        type: string
      DEBUG:
        required: true
        type: string
    outputs:
      result:
        description: "Result of the Quality Assurance"
        value: "success"

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-20.04
    container: python:3.10-slim-buster

    env:
      SECRET_KEY: ${{ inputs.SECRET_KEY || secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ inputs.ALLOWED_HOSTS || secrets.ALLOWED_HOSTS }}
      CORS_ALLOWED_ORIGINS: ${{ inputs.CORS_ALLOWED_ORIGINS || secrets.CORS_ALLOWED_ORIGINS }}
      DB_USER: ${{ inputs.DB_USER || secrets.DB_USER }}
      DB_PASSWORD: ${{ inputs.DB_PASSWORD || secrets.DB_PASSWORD }}
      DB_NAME: ${{ inputs.DB_NAME || secrets.DB_NAME }}
      DB_HOST: ${{ inputs.DB_HOST || secrets.DB_HOST }}
      DB_HOST_TEST: ${{ inputs.DB_HOST_TEST || secrets.DB_HOST_TEST }}
      CELERY_BROKER_URL: ${{ inputs.CELERY_BROKER_URL || secrets.CELERY_BROKER_URL }}
      DEBUG: ${{ inputs.DEBUG || secrets.DEBUG }}

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_HOST: ${{ secrets.DB_HOST }}

    steps:
      - uses: actions/checkout@v3

      - name: Install necessary tools
        run: apt-get update && apt-get install -y make

      - name: Install Dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          MOVIEMATE_SETTING_DATABASES: '{"default":{"ENGINE":"django.db.backends.postgresql", "PORT": 5432, "NAME":"${{ DB_NAME }}", "HOST":"${{ DB_HOST_TEST }}", "USER":"${{ DB_USER }}", "PASSWORD":"${{ DB_PASSWORD }}"}}'
