name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-20.04
    container: python:3.10-slim-buster

    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Install necessary tools
        run: apt-get update && apt-get install -y make

      - name: Install Dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test